In [1]:
import sqlite3
import pandas as pd
con = sqlite3.connect(r'C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\data\raw\ipl.db')
def q(sql):
    return pd.read_sql_query(sql, con)

In [2]:
q("""SELECT * FROM matches;""")

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [3]:
def run_sql_file(path):
    with open(path,'r') as f:
        script=f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [4]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\01_nulls_and_blanks_.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\01_nulls_and_blanks_.sql

In [5]:
q("""select count (*) as blank_before
from players
WHERE TRIM(field_pos)='';""")

   blank_before
0           612

In [6]:
q("""SELECT COUNT(*) AS  null_after
FROM v_players_clean
WHERE field_pos_clean is null;""")

   null_after
0         700

In [7]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\02_merge_categories.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\02_merge_categories.sql

In [8]:
q("""SELECT DISTINCT team_name
FROM teams
ORDER BY team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [9]:
q("""SELECT DISTINCT team_name_clean
FROM v_teams_clean
ORDER BY team_name_clean;""")

                team_name_clean
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14          Sunrisers Hyderabad

In [10]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\03_venue_names.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\03_venue_names.sql

In [11]:
q("""SELECT venue, COUNT(*) AS matches
FROM matches
WHERE venue IN ('Wankhede Stadium', 'Wankhede Stadium, Mumbai')
GROUP BY venue;""")

                      venue  matches
0          Wankhede Stadium       73
1  Wankhede Stadium, Mumbai       57

In [12]:
q("""SELECT venue, COUNT(*) AS matcheS
FROM matcheS
GROUP BY venue
ORDER BY matcheS DESC LIMIT 5;""")

                      venue  matcheS
0              Eden Gardens       77
1          Wankhede Stadium       73
2     M Chinnaswamy Stadium       65
3          Feroz Shah Kotla       60
4  Wankhede Stadium, Mumbai       57

In [13]:
q("""SELECT venue_clean,COUNT(*) AS matches
FROM v_matches_venue
GROUP BY venue_clean
ORDER BY matches DESC LIMIT 5;""")

                          venue_clean  matches
0                    Wankhede Stadium      130
1               M Chinnaswamy Stadium      104
2                        Eden Gardens      104
3              MA Chidambaram Stadium       95
4  Rajiv Gandhi International Stadium       87

In [14]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\04_dedupe_venues.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\04_dedupe_venues.sql

In [15]:
q("""SELECT COUNT(*) AS rows, COUNT(DISTINCT venue)AS names 
from venues;
""")

   rows  names
0    63     59

In [16]:
q("""select count(*),venue,city
from venues
group by venue
order by count(*) desc
limit 5;""")

   count(*)                                              venue       city
0         2                            Sharjah Cricket Stadium        NaN
1         2  Maharaja Yadavindra Singh International Cricke...     Mohali
2         2                Dubai International Cricket Stadium        NaN
3         2                 Dr DY Patil Sports Academy, Mumbai     Mumbai
4         1                   Zayed Cricket Stadium, Abu Dhabi  Abu Dhabi

In [17]:
q("""SELECT COUNT(*) AS rows, COUNT(DISTINCT venue)AS names 
from v_venues_clean;
""")

   rows  names
0    59     59

In [18]:
q("""select count(*),venue,city
from v_venues_clean
group by venue
order by count(*) desc
limit 10;""")

   count(*)                                             venue            city
0         1                  Zayed Cricket Stadium, Abu Dhabi       Abu Dhabi
1         1                          Wankhede Stadium, Mumbai          Mumbai
2         1                                  Wankhede Stadium          Mumbai
3         1      Vidarbha Cricket Association Stadium, Jamtha          Nagpur
4         1                                   SuperSport Park       Centurion
5         1                        Subrata Roy Sahara Stadium            Pune
6         1                                  St George's Park  Port Elizabeth
7         1                              Sheikh Zayed Stadium       Abu Dhabi
8         1                           Sharjah Cricket Stadium         Sharjah
9         1  Shaheed Veer Narayan Singh International Stadium          Raipur

In [19]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\05_city_fallback.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\05_city_fallback.sql

In [20]:
q("""select venue,count(*) as no_city
from matches
where city is null
group by venue;""")

                                 venue  no_city
0  Dubai International Cricket Stadium       33
1              Sharjah Cricket Stadium       18

In [21]:
q("""select city_clean from v_city_clean
where city_clean is null;
""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [22]:
q("""select city_clean
from v_city_clean;""")

          city_clean
0          Bangalore
1          Hyderabad
2               Pune
3             Rajkot
4             Indore
...              ...
1207           Delhi
1208  New Chandigarh
1209          Mumbai
1210       Ahmedabad
1211          Jaipur

[1212 rows x 1 columns]

In [23]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\06_season_year.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\06_season_year.sql

In [24]:
q("""select season,
count(*) as matches
from matches
where season = '2021/21'
group by season;
""")

Empty DataFrame
Columns: [season, matches]
Index: []

In [25]:
q("""SELECT season, 
COUNT(*) AS matches
FROM matches
WHERE season ='2020/21' 
GROUP BY season;
""")

    season  matches
0  2020/21       60

In [26]:
q("""SELECT DISTINCT season, season_year
FROM v_season WHERE season = '2020/21';""")

    season  season_year
0  2020/21         2020

In [27]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\07_win_definition.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\07_win_definition.sql

In [28]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\08_matches_clean.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\08_matches_clean.sql

In [29]:
q("""SELECT * from matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field
...,...,...,...,...,...,...,...,...,...
1207,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field
1208,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field
1209,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat
1210,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field
1211,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat

In [30]:
import ast 
import pandas as pd
d=pd.read_sql('select*from deliveries where fielders_involved is not null',con)
d['fielders']=d['fielders_involved'].apply(ast.literal_eval)
d=d.explode('fielders')
d['fielders'].value_counts().head(10)

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
WP Saha           139
SV Samson         134
RA Jadeja         129
RR Pant           119
SK Raina          119
Name: count, dtype: int64

In [ ]:
run_sql_file(r"C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\08_matches_clean.sql")

ran C:\Users\muhsi\OneDrive\Desktop\project_3.1_ipl\sql\practice\08_matches_clean.sql

: